name: Trigger Deploy
description: 'Trigger Deploy'
inputs:
  openshift-server:
    description: 'OpenShift server'
    required: true
  api-token:
    description: 'OpenShift service account API token'
    required: true
runs:
  using: 'composite'
  steps:
    # - name: List files in current directory
    #   run: ls -al
    #   shell: bash
    - name: Create the instance
      run: |
        ./.github/actions/migrate-db/restart_imagestreams.sh "${{ inputs.openshift-server }}" "${{ inputs.api-token }}"
      shell: bash