name: Migrate DB Schema
on:
    push:
      branches: [main, stage, develop]
    workflow_dispatch:
jobs:
    metadata:
        name: Get Metadata
        runs-on: ubuntu-20.04
        outputs:
          changed-apps: ${{ steps.get-changed-apps.outputs.changes }}
        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
              ref: ${{ github.ref }}
          - name: Get Changed Apps
            id: get-changed-apps
            uses: dorny/paths-filter@v2
            with:
              base: ${{ github.ref }}
              filters: |
                api:
                  - 'apps/api/prisma/migrations/**'
    migrate:
        name: Migrate DB Schema
        needs: metadata
        if: ${{ needs.metadata.outputs.changed-apps != '[]' && needs.metadata.outputs.changed-apps != '' }}
        runs-on: ubuntu-20.04
        environment:
          name: ${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'stage' && 'test' || 'dev' }}
        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
              ref: ${{ github.ref }}
          - name: 'migrate db'
            uses: ./.github/actions/migrate-db
            with:
                environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'stage' && 'test' || 'dev' }}
                openshift-server: ${{ secrets.OPENSHIFT_SERVER }}
                dev-token: ${{ secrets.OPENSHIFT_DEV_API_TOKEN }}
                database-url: ${{ secrets.DATABASE_URL }}
